name: teacher_attendance_app
description: "Aplikasi absensi guru menggunakan Flutter dan Firebase."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # myapp:
  #   path: .

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # State Management
  provider: ^6.0.5

  # UI
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0

  # Lokasi
  geolocator: ^10.1.1
  google_maps_flutter: ^2.5.3
  logging: ^1.1.0

  # Utilitas
  intl: ^0.18.1
  shared_preferences: ^2.2.0

  # Notifikasi
  flutter_local_notifications: ^9.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700